name: HolographicDisplays
main: com.gmail.filoghost.holograms.HolographicDisplays
version: 1.8.4

softdepend: [Multiverse-Core, MultiWorld, My Worlds, My_Worlds, ProtocolLib]

commands:
   holograms:
      description: Main command for HolographicDisplays.
      usage: /<command> (Startup error)
      aliases: [hd, holo, hologram]
   icon:
      description: Command to create unpickable floating items.
      usage: /<command> (Startup error)
      aliases: [icons, floatingitem, floatingitems]